/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 finn.glb
Author: lishenlong (https://sketchfab.com/lishenlong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adventure-time-finn-40405469c93c4cb08f67f523f1f2d245
Title: Adventure Time - Finn
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model() {
  const { nodes, materials } = useGLTF('/models/finn/finn.glb')
  return (
    <group  dispose={null} position={[0,0.85,0]} castShadow={true}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.head_copy20} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.bag0} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.bag1} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.tongue0} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.teeth10} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.teeth11} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.teeth12} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.teeth13} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.teeth0} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.teeth1} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.teeth2} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.teeth3} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.eyes0} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.eyes1} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.adventure_time_copy20} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.adventure_time_copy20} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.adventure_time_copy20} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.face0} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.shirt0} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.shirt1} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.shirt2} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.pants0} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.pants1} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.pants2} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Adventure_time0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/finn/finn.glb')
