/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 jake.glb
Author: Arnau Azorin (https://sketchfab.com/azorin)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/jake-the-dog-f8a17c174f244e11af1fb668895ddcae
Title: Jake The Dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model() {
  const { nodes, materials } = useGLTF('/models/jake/jake.glb')
  return (
    <group dispose={null} scale={0.03} position={[-1,0.85,0]}>
      <group scale={10.16}>
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_1.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_2.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_3.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_4.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_5.geometry} material={materials.PM3D_Cylinder3D4} />
        <mesh geometry={nodes.PM3D_Cylinder3D4_PM3D_Cylinder3D4_0_6.geometry} material={materials.PM3D_Cylinder3D4} />
      </group>
      <group scale={10.16}>
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_1.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_2.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_3.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_4.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_5.geometry} material={materials.PM3D_Cylinder3D6} />
        <mesh geometry={nodes.PM3D_Cylinder3D5_PM3D_Cylinder3D6_0_6.geometry} material={materials.PM3D_Cylinder3D6} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/jake/jake.glb')
