/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pb.glb -T --shadows
Author: pavito (https://sketchfab.com/pavito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/princess-bubblegum-988d525502734e55a808d0463d4ee33b
Title: Princess Bubblegum
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model() {
  const { nodes, materials } = useGLTF('/models/pbubblegum/pb-transformed.glb')
  return (
    <group  dispose={null} position={[-2.5, 0.95, 0]} rotation={[0, -1.2, 0]} scale={0.7}>
      <group position={[-0.04, 0.99, -0.04]} rotation={[0.12, 0, -Math.PI / 2]} scale={[1, 1.05, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.Material} position={[-0.32, 0.25, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.96, 1, 1]} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[0, 0, -0.08]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Material.004']} position={[-1.74, 0.31, 0.12]} rotation={[1.94, 0, 0]} scale={0.96} />
      <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Arms.004']} position={[0.17, 0.3, -0.38]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[0.09, 0.26, -0.09]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.003']} position={[0, 1.96, -0.08]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials['Arms.004']} position={[0, 0, -0.08]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['Dark.005']} position={[0.25, 0.77, 0.04]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials['Material.003']} position={[0, 1.96, -0.08]} rotation={[0, 0.16, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials['Arms.004']} position={[0, 0.32, 0.13]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials['Dark.005']} position={[0.27, 0.75, -0.04]} rotation={[0.02, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/pbubblegum/pb-transformed.glb')
